src/TrelloClone/Models/Board.cs
using System.Collections.Generic;

namespace TrelloClone.Models
{
  public class Board
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();
    }
}

src/TrelloClone/ViewModels/AddCard.cs
using System.ComponentModel.DataAnnotations;

namespace TrelloClone.ViewModels
{
    public class AddCard
    {
        public int Id { get; set; }

        [Required]
        public string Contents { get; set; }
    }
}

src/TrelloClone/ViewModels/BoardView.cs
using System.Collections.Generic;

namespace TrelloClone.ViewModels
{
    public class BoardView
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Column> Columns { get; set; } = new List<Column>();

        public class Column
        {
            public int Id { get; set; }
            public string Title { get; set; }
            public List<Card> Cards { get; set; } = new List<Card>();
        }

        public class Card
        {
            public int Id { get; set; }
            public string Content { get; set; }
        }
    }
}

src/TrelloClone/Controllers/Api/BoardController.cs
using Microsoft.AspNetCore.Mvc;
using TrelloClone.Services;
using TrelloClone.ViewModels;

namespace TrelloClone.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class BoardController : ControllerBase
    {
        private readonly BoardService _boardService;

        public BoardController(BoardService boardService)
        {
            _boardService = boardService;
        }

        [HttpPost("movecard")]
        public IActionResult MoveCard([FromBody] MoveCardCommand command)
        {
            _boardService.Move(command);

            return Ok(new 
            { 
                Moved = true
            });
        }
    }
}

src/TrelloClone/Controllers/BoardController.cs
using Microsoft.AspNetCore.Mvc;
using TrelloClone.Services;
using TrelloClone.ViewModels;

namespace TrelloClone.Controllers
{
    public class BoardController : Controller
    {
        private readonly BoardService _boardService;

        public BoardController(BoardService boardService)
        {
            _boardService = boardService;
        }

        public IActionResult Index(int id)
        {
            var model = _boardService.GetBoard(id);

            return View(model);
        }

        public IActionResult Details(int id)
        {
            return View(_boardService.GetBoard(id));
        }

        public IActionResult AddCard(int id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCard(AddCard viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            _boardService.AddCard(viewModel);
            
            return RedirectToAction(nameof(Index), new { id = viewModel.Id });
        }
    }
}

src/TrelloClone/Controllers/CardController.cs
using Microsoft.AspNetCore.Mvc;
using TrelloClone.Services;
using TrelloClone.ViewModels;

namespace TrelloClone.Controllers
{
    public class CardController : Controller
    {
        private readonly CardService _cardService;

        public CardController(CardService cardService)
        {
            _cardService = cardService;
        }
        
        [HttpGet]
        public IActionResult Details(int id)
        {
            var viewModel = _cardService.GetDetails(id);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Update(CardDetails cardDetails)
        {
            _cardService.Update(cardDetails);

            TempData["Message"] = "Saved card Details";

            return RedirectToAction(nameof(Details), new { id = cardDetails.Id });
        }
    }
}

src/TrelloClone/Views/Board/AddCard.cshtml
@model TrelloClone.ViewModels.AddCard
@{
    ViewData["Title"] = "AddCard";
}

<div class="container">
    <div class="row">
        <h2>Add Card</h2>
        <form asp-action="AddCard" asp-controller="Board">
            <div asp-validation-summary="All" class="red-text"></div>
            <label>Contents</label>
            <input type="text" asp-for="Contents"/>
            <button style="background-color: grey" type="submit" class="btn">Add Card</button>
        </form>
    </div>
</div>

src/TrelloClone/Views/Board/Index.cshtml
@model TrelloClone.ViewModels.BoardView

@{
    ViewData["Title"] = "Index";
}
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf

@functions {
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

<input type="hidden"
       id="RequestVerificationToken"
       name="RequestVerificationToken"
       value="@GetAntiXsrfRequestToken()">

<script>
    $(function () {
        $(".draggable").draggable({
            revert: "invalid"
        });

        $('.column').droppable({
            accept: '.draggable',
            drop: function (event, ui) {
                var dropped = ui.draggable;
                var droppedOn = $(this);
                $(dropped).detach().css({ top: 0, left: 0 }).appendTo(droppedOn);

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json",
                    url: "/api/Board/movecard",
                    beforeSend: function (request) {
                        request.setRequestHeader("RequestVerificationToken", $('#RequestVerificationToken').val());
                    },
                    data: JSON.stringify({ cardId: dropped[0].id, columnId: droppedOn[0].id }),
                });
            }
        });
    });
</script>

<div class="container">

    <h4 style="text-align:center">@Model.Title</h4>

    <div class="row">
        <div class="col s10">
            <a style="background-color: grey" asp-controller="Board"
               asp-action="AddCard"
               asp-route-id="@Model.Id"
               class="wave-effect waves-light btn">
                Add A Card
            </a>
        </div>
    </div>

    <div class="row">
        @foreach (var column in Model.Columns)
        {
            <div class="col m4">

                <h3 style="text-align:center">@column.Title</h3>

                <div class="column" style="min-height: 600px" id="@column.Id">

                    @foreach (var card in column.Cards)
                    {
                        <div class="card blue-grey darken-1 draggable" id="@card.Id">
                            <div class="card-content">
                                <p>
                                    <a asp-controller="Card" asp-action="Details"
                                       asp-route-id="@card.Id" class="white-text">
                                        @card.Content
                                    </a>
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
</div>